### ISSUE TITLE
exFAT Freeze while inserting

### ISSUE THREAD

**Issue by xadox-1st** [d0k3/EmuNAND9#11]
While using the select button in main menu for ejecting the sd card and inserting a new SanDisk 64GB card EmuNAND9 was freezing. Was occuring multiple times.

Since the card was delivered with pre formated exFAT I delete the partitions on the card with Windows disk part (clean option).

After that EmuNAND9 was working with the new 64GB card.

Using: EmuNAND9 20160420

**Comment by d0k3** [comment]
Alright, we just tried to reproduce this, with a 64GB exFAT formatted card - we had no issues, so something else caused your freezing. Any idea? if you can, retry with another exFAT formatted card, too.

**Comment by d0k3** [comment]
Alright, there hasn't been any updates in a long while here. @xadox-1st is this still an issue and can you give me more information? Otherwise I'll close this.
