### ISSUE TITLE
can not restore nand.

### ISSUE THREAD

**Issue by jiachunpeng** [d0k3/EmuNAND9#15]
i use EmuNAND9(20160201) to backup nand, there is no .sha file and otphelper can not recognize it's header. can i restore nand without EmuNAND9(20160201)?

**Comment by d0k3** [comment]
This sounds like this backup got corrupted after it was dumped. Try Decrypt9's force restore, but only on EmuNAND. Don't restore this to SysNAND(!!!).

**Comment by jiachunpeng** [comment]
thanks for your reply.
otphelper said all my other backups may lead n3ds to be bricked. 
i have downgraded 3ds to 2.1 and will try to recover the sysnand.

**Comment by d0k3** [comment]
Maybe ask in the GBAtemp thread or on #3dshacks on Rizon? Also include the logfile content in that case.

If you ask in these places, other people can help you, too, and Github issues isn't a place for support normally.

**Comment by d0k3** [comment]
Any new information on this?

**Comment by jiachunpeng** [comment]
I found the data in nand file is stange,and still wrote it to sysnand to see what would happen,then n3ds crash while booting,then I tried many ways to write data into it's memory chip and failed, then I bought a new n3ds :>

**Comment by d0k3** [comment]
I specifically told you not to restore it to SysNAND. You could have easily tried it out on EmuNAND. Anyways, you can still save that N3DS with a hardmod, or, if you can't do it, it still has resell value, even more if you still got a valid NAND backup.

Closing this now, as the source of the corruption is most likely outside of my tools.
