### ISSUE TITLE
D-pad bugs

### ISSUE THREAD

**Issue by ph1signals** [d0k3/EmuNAND9#16]
Hi guys,

I encouter a major bug with EmuNAND9 on all last versions.

I can't navigate with the d-pad. If I click 'down' the line come back directly at the first position.
It's possible to navigate by holding 'down' and 'right' or 'left' buttons. but impossible to pass the sequential test '

It's very strange, I just encouter this problem on emunand. I try all the last versions with a fresh starter pack, format the console etc. I'm on 9.2.0.20.E

It's possible to have a version with analog pad supported ? regards

**Comment by ihaveamac** [comment]
are one of your shoulder buttons (L/R) stuck/being held down?

**Comment by ph1signals** [comment]
hi ihaveamac

no. I can use all the buttons without problems using the console in others menus and applications

**Comment by d0k3** [comment]
Well... you notice you are the only one with this issue, so it must have to do with your hardware? Anyways, I suggest you also try Decrypt9WIP and GodMode9. Report back if you have issues in those two tools as well.

**Comment by d0k3** [comment]
@ph1signals - anything new on this issue? If not I will close this, as it looks like a hardware error on your side.

**Comment by ph1signals** [comment]
Hi,

the problem comes from a inversed buttons (L/R)

sorry for this thread

**Comment by d0k3** [comment]
No problem, closing this now
