### ISSUE TITLE
Switch back to 32KB Cluster Size

### ISSUE THREAD

**Issue by cheatfreak47** [d0k3/EmuNAND9#18]
There's a case to be made for 64KB Cluster Size, but there's a known issue with GBA games where the screen gets wrapped improperly for some reason, especially on larger (and therefore slower) SD cards.

Changing the cluster size to 32KB instead of 64KB seems to entirely fix this issue, and since a lot of people use EmuNAND9 to format their cards, it'd be wise to revert back to 32KB instead.

Relevant issues from other repos:
https://github.com/AuroraWright/Luma3DS/issues/142

**Comment by d0k3** [comment]
Okay, this is bad. People actually want 64k clustersize, and it actually serves to improve loading speeds in most cases.

Will that GBA game issue pop up in each and every case or is it limited to some specific cases?

**Comment by cheatfreak47** [comment]
Based on my testing of the issue, it seems much more prevalent on larger cards and on n3DS systems, but that's only based on my limited testing of the issue. The pattern I noticed was that the larger the card gets, the more often it happens and it still can happen on both the o3DS and n3DS, but happens on the n3DS significantly more often for whatever reason. What's strange about it is that the issue happens only _sometimes_ for whatever reason and when it does, pressing the home button repeatedly causes the wrapping to _move around._

Anyhow, the evidence I have for this may or may not be circumstantial, because I didn't exactly do _exhaustive_ testing, but the issue I can confirm does only happen on cards with 64KB cluster size.

I believe the issue can happen to everyone, but since not everyone will play GBA games so it's not an issue that pops up crazy often. Some people just ignore it when it happens and restart their system until the game starts properly but that's hardly intuitive, I'd say. Some people actually mash the hell out of their Home Button until the screen moves into the correct position, which... probably isn't good for all those poor home buttons out there.

I haven't really noticed any speed difference in the home menu and moving in and out of games since I switched back to 32KB, and in the case of GBA games, 32KB actually seems faster for booting GBA games for whatever reason. It seems like AGB_FIRM really wants a 32KB cluster size I guess. ¯_(ツ)_/¯

It could be beneficial to just have an option during the formatting that just says
"What cluster size would you like?
<32KB> or <64KB> 
32KB is recommended. 64KB may be faster for some cards, 
but also can cause video issues in GBA Virtual Console titles."

This is off topic but the next version of EmuNAND9 should totally use the new font, it looks great.

**Comment by Masamune3210** [comment]
I have never had this issue with my o3DS XL with a 64GB card and running Luma 6.0.1 and 11.0

**Comment by cheatfreak47** [comment]
@deadair3210 How often do you play GBA games? 
Like I said, the issue happens mostly on n3DS consoles. Though I did have it pop up once or twice on my o3DS.

**Comment by Masamune3210** [comment]
I have multiple legitimate and custom GBA games on my 3DS, as it's one of my favorite handhelds. I tend to play them quite a bit, mostly RPG's and Platformers, The only issue I have ever had is a couple of games just not working correctly, such as Golden Sun and the other games that pushed the GBA hardware

**Comment by cheatfreak47** [comment]
This is semi-offtopic but what was the issue with Golden Sun, out of curiosity? @deadair3210

**Comment by Masamune3210** [comment]
For some reason, I could never get it to boot correctly, would always either freeze on a black screen or not work correctly in one way or another

**Comment by cheatfreak47** [comment]
You might have had a bad rom or setup the footer incorrectly then, Golden Sun and Golden Sun The Lost Age work fine for me. @deadair3210 Try Asdolo's new injector.

Sorry for the off topic posts, getting back to the issue- 

Like I said the issue seems a lot more rare on the o3DS, I think I only ever had it happen once on there, so there's probably truth to what @deadair3210 is saying.

**Comment by Masamune3210** [comment]
I havent tried the new injector, it might have been something that I did.

Back on topic, as far as I know, the AGB_FIRM is the same between the n3ds and the o3ds, so I dont know what would cause the issue to be n3ds specific unless it is some problem with the hardware

**Comment by james-d-elliott** [comment]
I'd suggest having the safe default of 32kb size, and adding the option for those who want to use it, of 64kb. @d0k3

**Comment by d0k3** [comment]
Agreed and included in https://github.com/d0k3/EmuNAND9/commit/ea8bd4823d305011b3062394c9bb653cc29f7fe6

GodMode9 will retain the ability to format with 64k cluster size.
