### ISSUE TITLE
Formatting with EmuNAND9 should wipe the magic used to detect old emunands

### ISSUE THREAD

**Issue by ksanislo** [d0k3/EmuNAND9#19]
Luma3DS's emuNAND/redNAND detection looks for a magic string in the image to identify things, not the partition table. The quick format option to remove an emunand will leave this on the SD card even though the emuNAND has been corrupted, and can cause ARM9 exceptions on boot.

I know this is really a [Luma3DS problem](https://github.com/AuroraWright/Luma3DS/blob/master/source/emunand.c#L28), and they should be checking the partition table to see if space is reserved, but could you have this wipe those blocks while reformatting just to avoid the trouble?

-Ken

**Comment by d0k3** [comment]
Included in https://github.com/d0k3/EmuNAND9/commit/19724f45c003b77d25b101a8ad72511c9e330522
