### ISSUE TITLE
support Multi EmuNAND Create

### ISSUE THREAD

**Issue by srwgin** [d0k3/EmuNAND9#20]
Is it possible support Multi EmuNAND Create
add blew    function
Multi EmuNAND Options
Format Multi EmuNAND 2/3/4
Clone your SysNAND to EmuNAND1 / RedNAND1
Clone your SysNAND to EmuNAND2 / RedNAND2
Clone your SysNAND to EmuNAND3 / RedNAND3
Clone your SysNAND to EmuNAND4 / RedNAND4
Backup your EmuNAND1 / RedNAND1 to a file
Backup your EmuNAND2 / RedNAND2 to a file
Backup your EmuNAND3 / RedNAND3 to a file
Backup your EmuNAND4 / RedNAND4 to a file
Restore your EmuNAND1 / RedNAND1 from a backup
Restore your EmuNAND2 / RedNAND2 from a backup
Restore your EmuNAND3 / RedNAND3 from a backup
Restore your EmuNAND4 / RedNAND4 from a backup
Convert your EmuNAND1/2/3/4 -> RedNAND1/2/3/4 or vice versa

**Comment by d0k3** [comment]
This has been brought up earlier, and the decision is, no, EmuNAND9 won't get Multi EmuNAND setup support. With A9LH being a thing now, EmuNAND in general has lost some if it's earlier relevance, and multi EmuNAND always has been somewhat of a niché thing. This also being a lot of work, the decision is to not add it.

You can use GM9 to properly format your SD card for multiple EmuNANDs, then use Multi EmuNAND Tool on PC to set it up. D9 and HG9 can handle multiple EmuNANDs.
