### ISSUE TITLE
EmuNAND9.nds Concerns

### ISSUE THREAD

**Issue by kamenrider-darkglass** [d0k3/EmuNAND9#22]
Since boot9strap is incompatible with the .bin version of EmuNAND9, I decided to use the .nds version with my flashcart instead. My concern here is that when I entered the .nds version of EmuNAND9, I arrived at a menu that includes : >>Cakes ROP Installer<< as the title. 

I pressed A on the 4.x EmuNAND9 option and something happened and then my console rebooted. Did I somehow fuck something up? I really need to know what happened because I am a bit paranoid right now. 

I have boot9strap v1.2 and Luma3DS v7.0.5 btw.

**Comment by d0k3** [comment]
[CakesROP](https://github.com/mid-kid/CakesROP) issue (= not a GM9 one), and it's doubtful this will still work on boot9strap anyways.
