### ISSUE TITLE
Can I restore GW Emunand backup on my SD after Complete Emunand Setup?

### ISSUE THREAD

**Issue by Boured** [d0k3/EmuNAND9#3]
Self explanitory.

Sorry this isn't much of a issue, I just wanted confirmation from the actual maker of the software so please forgive me if I'm doing something wrong.

**Comment by Boured** [comment]
To clarify, my emunand was made with Gateway SD Formatting.

**Comment by d0k3** [comment]
This is the wrong place to ask. The issues section on Github is for reporting bugs and suggesting improvements. That being said, yes, EmuNAND9 will restore any valid NAND backup. I suggest you make another EmuNAND backup in EmuNAND9 _before_ proceeding with the setup, though.

If there's more to ask, ask in the [official thread on GBAtemp](http://gbatemp.net/threads/release-emunand9tool-open-source-emunand-formatter-manager.405921/).
