### ISSUE TITLE
EmuNAND partition size Question

### ISSUE THREAD

**Issue by tmc9031** [d0k3/EmuNAND9#4]
After using, EmuNAND9 format EmuNAND partition size is 1.2GB
But Gateway format EmuNAND partition size is 2GB
So, whether EmuNAND9 partition is NOT enough for future EmuNAND system update ???

**Comment by d0k3** [comment]
1.2GB is the size of your NAND flash chip, The actual size of the NAND data is [even smaller](https://3dbrew.org/wiki/Flash_Filesystem). The actual size of the CTRNAND FAT partition inside the NAND is smaller than the NAND data, that partition's size is fixed (ie, it can't be bigger / smaller than Nintendo intended), and that's the only place where update data goes.

So, no, there will never be problems with future updates. Closing this...

**Comment by tmc9031** [comment]
thank your tips, i used EmuNAND9 create emu part, and update emu v10.5.0-30
everythis is fine, thanks again ~~
