### ISSUE TITLE
Use partition type 0x1C for EmuNAND partition

### ISSUE THREAD

**Issue by GerbilSoft** [d0k3/EmuNAND9#5]
Commit 840c7e1 added an MBR entry for the EmuNAND partition, which is a good idea overall. However, some OSes may show the drive as "unformatted", which may lead to an accidental format as FAT32, thus destroying the EmuNAND.

Instead of partition type 0x0C, consider using type 0x1C. This is used by various recovery partitions to indicate a "hidden" FAT32 partition, so Windows won't try mounting it as a regular drive.

Reference: https://en.wikipedia.org/wiki/Partition_type

**Comment by d0k3** [comment]
Handled in https://github.com/d0k3/EmuNAND9/commit/e448e1f2e6b54b23e704da76587c8eed3cac5fa2
