### ISSUE TITLE
(Inquiries) EMUNand to REDNand Convertion

### ISSUE THREAD

**Issue by Committee** [d0k3/EmuNAND9#6]
Not really an issue but more like a couple of questions:
1. If I convert my current EMUNand to REDNand will it free up space on the useable partition? 
2. Wil I have to recopy anything if I convert my current EMUNand?
3. Will I retain the current installed CIAs when I convert?
4. How much space difference am I to expect when I convert Emunand to REDNand? (current Emunand for N3DS is a little around 1.8gb)

**Comment by d0k3** [comment]
The new readme file (just updated) should answer all your questions, just check it out!
