### ISSUE TITLE
Linux compatible

### ISSUE THREAD

**Issue by master-key-g** [d0k3/EmuNAND9#8]
Hi d0k3 can your change your make file on emunand9 startergen that any one how is on linux can make this starter bin to.
For the bat file is only on line how need changed cp = linux, copy = windows

**Comment by d0k3** [comment]
Should be fine after the latest commit. I'll leave that open until you try and tell me if it works.

**Comment by mariogamer2** [comment]
Work fine thank

**Comment by d0k3** [comment]
Closing this now thank you!
